name: WarnPlayer
version: 2.0.0
api: [3.0.0]
author: MCrafters
main: WarnPlayer\Main
commands:
  warn:
    description: Warn A Player!
    usage: "/warn <player> <reason>"
  warns:
    description: Checks a list of warnings a player has.
    usage: "/warns <Player>"
permissions:
  player.warn:
    default: op
  player.warns:
    default: op
