name: WarnPlayer
version: 2.0.0
api: [3.0.0]
author: MCrafters
main: WarnPlayer\Main
commands:
  warn:
    description: Warn A Player!
    usage: "/warn <player> <reason>"
    permission: player.warn
permissions:
  player.warn:
    default: op
